#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : php-gRPC
Version  : 1.48.1
Release  : 38
URL      : https://pecl.php.net/get/grpc-1.48.1.tgz
Source0  : https://pecl.php.net/get/grpc-1.48.1.tgz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
BuildRequires : buildreq-php

%description
# Overview
This directory contains source code for PHP implementation of gRPC layered on
shared C library. The same installation guides with more examples and
tutorials can be seen at [grpc.io](https://grpc.io/docs/languages/php/quickstart).
gRPC PHP installation instructions for Google Cloud Platform is in
[cloud.google.com](https://cloud.google.com/php/grpc).

%prep
%setup -q -n grpc-1.48.1
cd %{_builddir}/grpc-1.48.1

%build
## build_prepend content
export GCC_IGNORE_WERROR=1
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
phpize
%configure --disable-static
make  %{?_smp_mflags}

%install
mkdir -p %{buildroot}/usr/share/package-licenses/php-gRPC
cp %{_builddir}/grpc-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/php-gRPC/242ec6abfdd8c114f2e803b84934469c299348fc || :
%make_install


%files
%defattr(-,root,root,-)
